import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/main.scss";
import Header from "../widgets/Header";
import Footer from "../components/Footer";
import SmoothScroll from "../components/SmoothScroll";
import AuthProvider from "../components/AuthProvider";
import { CurrencyProvider } from "../context/CurrencyContext";
import AOSProvider from "../components/AosProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AuthProvider>
          <CurrencyProvider>
            <AOSProvider>
              <SmoothScroll>
                <Header />
                <div className="flex-1">
                  {children}
                </div>
                <Footer />
              </SmoothScroll>
            </AOSProvider>
          </CurrencyProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
